<?php
namespace Dev\Scaffold;

class MakeModule
{
    public function run(string $name): void
    {
        $safe = preg_replace('/[^a-zA-Z0-9_]/', '', $name);
        if (!$safe) throw new \RuntimeException('Invalid module name');

        $dir = ROOT_PATH . '/engine/Modules/' . strtolower($safe);
        if (is_dir($dir)) throw new \RuntimeException('Module already exists: ' . $safe);

        @mkdir($dir . '/Controllers', 0775, true);
        @mkdir($dir . '/Views', 0775, true);
        @mkdir($dir . '/Migrations', 0775, true);

        file_put_contents($dir . '/module.json', json_encode([
            'name' => $safe,
            'version' => '1.0.0',
            'description' => 'Generated module',
        ], JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));

        $ctrl = <<<PHP
<?php
namespace Modules\{mod}\Controllers;

use Template\Template;

class IndexController
{
    public function index()
    {
        \$tpl = new Template();
        \$tpl->render('{mod}/index.tpl', [
            'title' => '{mod} module',
        ]);
    }
}
PHP;
        $ctrl = str_replace('{mod}', strtolower($safe), $ctrl);
        file_put_contents($dir . '/Controllers/IndexController.php', $ctrl);

        $tpl = "<h1>{title}</h1>\n<p>Generated by CajeerEngine make:module</p>\n";
        @mkdir(ROOT_PATH . '/templates/default/' . strtolower($safe), 0775, true);
        file_put_contents(ROOT_PATH . '/templates/default/' . strtolower($safe) . '/index.tpl', $tpl);
    }
}
