<?php
namespace Dev\Scaffold;

class MakeContent
{
    public function run(string $type): void
    {
        $safe = preg_replace('/[^a-zA-Z0-9_-]/', '', $type);
        if (!$safe) throw new \RuntimeException('Invalid type');

        $dir = ROOT_PATH . '/engine/Content/Types/' . strtolower($safe);
        if (is_dir($dir)) throw new \RuntimeException('Content type already exists: ' . $safe);

        @mkdir($dir, 0775, true);

        $schema = [
            'type' => strtolower($safe),
            'fields' => [
                ['name'=>'title','type'=>'string','required'=>true],
                ['name'=>'slug','type'=>'string','required'=>true],
                ['name'=>'content','type'=>'text','required'=>false],
            ],
        ];
        // fix booleans for php later
        file_put_contents($dir . '/schema.json', json_encode($schema, JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));

        $readme = "# Content Type: {$safe}

Generated by `make:content`.

- Edit `schema.json`
- Add business logic in your modules/controllers.
";
        file_put_contents($dir . '/README.md', $readme);
    }
}
