<?php
return [
  '/' => ['news', 'index'],
  '/news' => ['news', 'index'],
  '/news/view' => ['news', 'view'],
  '/admin' => ['admin', 'index'],
    '/admin/themes' => ['admin', 'themesIndex'],
    '/admin/themes/switch' => ['admin', 'themesSwitch'],
    '/admin/marketplace/status' => ['admin', 'marketplaceStatus'],
    '/admin/ui-builder' => ['admin', 'uiBuilderIndex'],
    '/admin/ui-builder/save' => ['admin', 'uiBuilderSave'],
    '/admin/marketplace/themes' => ['admin', 'marketplaceThemes'],
    '/admin/marketplace/plugins' => ['admin', 'marketplacePlugins'],
,
  '/page' => ['pages', 'view'],
  '/category' => ['category', 'view'],
,
    '/sitemap.xml' => ['seo', 'sitemap'],
    '/robots.txt' => ['seo', 'robots']
    '/api/v1/ping' => ['api', 'ping'],
    '/api/v1/content' => ['api', 'contentIndex'],
    '/api/v1/content/get' => ['api', 'contentGet'],
    '/api/v1/content/create' => ['api', 'contentCreate'],
    '/api/v1/content/update' => ['api', 'contentUpdate'],
    '/api/v1/content/delete' => ['api', 'contentDelete'],
    '/api/v1/content/publish' => ['api', 'contentPublish'],
    '/api/v1/categories' => ['api', 'categoriesIndex'],
    '/api/v1/types' => ['api', 'typesIndex'],
    '/api/v1/admin/me' => ['api', 'adminMe'],
    '/api/v1/admin/stats' => ['api', 'adminStats'],
    '/api/v1/ui/blocks' => ['api', 'uiBlocks'],
    '/api/v1/ui/get' => ['api', 'uiGet'],
    '/api/v1/ui/save' => ['api', 'uiSave'],
    '/api/v1/ui/preview' => ['api', 'uiPreview'],
];
